-- PostgreSQL import commands for CSVs generated by:
-- python3 scripts/generate_asset_management_data.py
--
-- In psql, set the absolute project path first:
-- \set project_root '/Users/seanharvey/Documents/asset_management_growth_analytics'

\set dim_clients_csv :project_root '/data/raw/dim_clients.csv'
\set dim_funds_csv :project_root '/data/raw/dim_funds.csv'
\set dim_accounts_csv :project_root '/data/raw/dim_accounts.csv'
\set fact_market_returns_csv :project_root '/data/raw/fact_market_returns.csv'
\set fact_transactions_csv :project_root '/data/raw/fact_transactions.csv'
\set fact_daily_balances_csv :project_root '/data/raw/fact_daily_balances.csv'

\copy dim_clients from :'dim_clients_csv' with (format csv, header true);
\copy dim_funds from :'dim_funds_csv' with (format csv, header true);
\copy dim_accounts from :'dim_accounts_csv' with (format csv, header true, null '');
\copy fact_market_returns from :'fact_market_returns_csv' with (format csv, header true);
\copy fact_transactions from :'fact_transactions_csv' with (format csv, header true);
\copy fact_daily_balances from :'fact_daily_balances_csv' with (format csv, header true);
